sonar.projectKey=IvogGabrielIFBA_Eng_Soft_2-2026
sonar.organization=ivoggabrielifba

sonar.python.version=3.13
sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/build/**,**/htmlcov/**,**/.venv/**,**/.pytest_cache/**
